Ryan_Budget/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ryan_Budget.Models;
using Microsoft.AspNet.Identity;
using System.IO;

namespace Ryan_Budget.Controllers
{
    [RequireHttps]
    public class TransactionsController : UserNames
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Transactions
        [Authorize]
        public ActionResult Index()
        {
            var user = db.Users.Find(User.Identity.GetUserId());           
            var transactions = user.Household.Accounts.SelectMany(a => a.Transactions);
            return View(transactions.OrderByDescending(t=>t.Id).ToList());
        }

        // GET: Transactions/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.AccountId = new SelectList(db.Accounts, "Id", "Name");           
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            var expenses = db.Categories.Where(c => c.Type == false);
            var incomes = db.Categories.Where(c => c.Type == true);
            ViewBag.Expenses = expenses;
            ViewBag.Incomes = incomes;
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Amount,AccountId,CategoryId,Type,Description,AuthorUserId,UpdateUserId,Documentation,Reconciled,TransactionDate,Created,Updated,Status")] Transaction transaction, HttpPostedFileBase image)
        {
            Account account = db.Accounts.Find(transaction.AccountId);
            var oldBal = account.Balance;

            if (ModelState.IsValid)
            {           
                var user = db.Users.Find(User.Identity.GetUserId());
                var userid = user.Id;
                var created = System.DateTime.Now;

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Receipts/"), fileName));
                    transaction.Documentation = "~/Receipts/" + fileName;
                }

                transaction.AuthorUserId = user.Id;
                transaction.Created = System.DateTimeOffset.Now;
                if (transaction.Type == false)
                {
                    transaction.Amount = transaction.Amount * -1;
                }
                account.Balance = account.Balance + transaction.Amount;
                account.Updated = System.DateTimeOffset.Now;
                db.Transactions.Add(transaction);
                db.SaveChanges();

                if (oldBal > 0 && account.Balance < 0)
                {
                    foreach (var member in user.Household.Users)
                    {
                        Notification n = new Notification()
                        {
                            HouseholdId = user.Household.Id,
                            AccountId = account.Id,
                            AuthorUserId = userid,
                            UserToNotifyId = member.Id,
                            Created = created,
                            Type = "Overdraft Notice",
                            Description = account.Name + " is now overdrafted",
                        };
                        db.Notifications.Add(n);
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index", "Home");
            }

            ViewBag.AccountId = new SelectList(db.Accounts, "Id", "Name", transaction.AccountId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", transaction.CategoryId);
            var expenses = db.Categories.Where(c => c.Type == false);
            var incomes = db.Categories.Where(c => c.Type == true);
            ViewBag.Expenses = expenses;
            ViewBag.Incomes = incomes;
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }

        // GET: Transactions/Edit/5
        [Authorize]
        public ActionResult Edit(int? id, int? act)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != transaction.Account.HouseholdId)
            {
                return RedirectToAction("Warning", "Household");
            }

            if (act != null)
            {
                ViewBag.Account = transaction.AccountId;
            }

            ViewBag.Accounts = user.Household.Accounts.ToList();
            ViewBag.AccountId = new SelectList(ViewBag.Accounts, "Id", "Name", transaction.AccountId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", transaction.CategoryId);
            var expenses = db.Categories.Where(c => c.Type == false);
            var incomes = db.Categories.Where(c => c.Type == true);
            ViewBag.Expenses = expenses;
            ViewBag.Incomes = incomes;
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Amount,AccountId,CategoryId,Type,Description,AuthorUserId,UpdateUserId,Documentation,Reconciled,TransactionDate,Created,Updated,Status")] Transaction transaction, HttpPostedFileBase image, int? act)
        {

            Transaction oldTrans = db.Transactions.AsNoTracking().FirstOrDefault(t => t.Id == transaction.Id);

            var user = db.Users.Find(User.Identity.GetUserId());
            var userid = user.Id;
            var created = System.DateTime.Now;
            Account account = db.Accounts.Find(transaction.AccountId);
            Account oldAccount = db.Accounts.Find(oldTrans.AccountId);
            var oldBal = account.Balance;        

            if (ModelState.IsValid)
            {
                transaction.Updated = System.DateTimeOffset.Now;
                transaction.UpdateUserId = user.Id;
                transaction.AuthorUserId = user.Id;
                if (transaction.Type == false)
                {
                    transaction.Amount = transaction.Amount * -1;
                }

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Receipts/"), fileName));
                    transaction.Documentation = "~/Receipts/" + fileName;
                }

                db.Transactions.Attach(transaction);
                db.Entry(transaction).Property("Amount").IsModified = true;
                db.Entry(transaction).Property("AccountId").IsModified = true;
                db.Entry(transaction).Property("CategoryId").IsModified = true;
                db.Entry(transaction).Property("Type").IsModified = true;
                db.Entry(transaction).Property("Description").IsModified = true;
                db.Entry(transaction).Property("Documentation").IsModified = true;
                db.Entry(transaction).Property("Updated").IsModified = true;
                db.Entry(transaction).Property("TransactionDate").IsModified = true;
                db.SaveChanges();

                if (oldTrans?.Amount != transaction.Amount)
                {
                    account.Balance = account.Balance - oldTrans.Amount + transaction.Amount;
                    account.Updated = System.DateTimeOffset.Now;
                    db.SaveChanges();

                    if (oldBal > 0 && account.Balance < 0)
                    {
                        foreach (var member in user.Household.Users)
                        {
                            Notification n = new Notification()
                            {
                                HouseholdId = user.Household.Id,
                                AccountId = account.Id,
                                AuthorUserId = userid,
                                UserToNotifyId = member.Id,
                                Created = created,
                                Type = "Overdraft Notice",
                                Description = account.Name + " is now overdrafted",
                            };
                            db.Notifications.Add(n);
                            db.SaveChanges();
                        }
                    }
                }

                if (oldTrans?.AccountId != transaction.AccountId)
                {
                    oldAccount.Balance = oldAccount.Balance - oldTrans.Amount;
                    transaction.Account.Balance = transaction.Account.Balance + transaction.Amount;
                    db.SaveChanges();                   
                }

                if (act != null)
                {
                    return RedirectToAction("Details", "Accounts", new { id = act });
                }

                return RedirectToAction("Index", "Home");
                
            }
            ViewBag.AccountId = new SelectList(db.Accounts, "Id", "Name", transaction.AccountId);

Ryan_Budget/Views/Transactions/Create.cshtml
@model Ryan_Budget.Models.Transaction
@using Microsoft.AspNet.Identity;
@using Ryan_Budget.Models;

@{
    ViewBag.Title = "Create";
    ApplicationDbContext db = new ApplicationDbContext();
    var user = db.Users.Find(User.Identity.GetUserId());
    Layout = null;
}

@using (Html.BeginForm("Create", "Transactions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="widget" style="background: none">
        <div class="widget-content">
            <form class="form-horizontal" role="form">
                <fieldset class="transactions">
                    <div class="form-group">
                        <label for="ticket-email" class="col-sm-3 control-label">Transaction Date</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                <input type="text" id="datepicker" name="TransactionDate" class="form-control" required>
                            </div>
                        </div>
                    </div><br /><br /><br />
                    <div class="form-group">
                        <label for="ticket-type" class="col-sm-3 control-label">Account</label>
                        <div class="col-sm-9">
                            <select id="ticket-type" name="AccountId" class="select-ticket-type" required>
                                @if (user.Household.Accounts != null)
                                {
                                    @*if (user.Household.Accounts.Count() > 1)
                                    {
                                    <option disabled selected>- - - - - - - - - - - - - </option>
                                    }*@
                                    foreach (var account in user.Household.Accounts)
                                    {
                                        <option value="@account.Id">@account.Name</option>
                                    }
                                }
                            </select>
                            @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
                        </div>
                    </div><br /><br />
                    <div class="form-group">
                        <label for="ticket-priority" class="col-sm-3 control-label">Category</label>
                        <div class="col-sm-9">
                            <select id="multiselect6" name="CategoryId" class="select-ticket-priority" required>
                                <optgroup label="Expense">          
                                    @foreach (var category in ViewBag.Expenses)
                                    {
                                        <option value="@category.Id">@category.Name</option>
                                    }
                                </optgroup>
                                <optgroup label="Income">
                                    @foreach (var category in ViewBag.Incomes)
                                    {
                                        <option value="@category.Id">@category.Name</option>
                                    }
                                </optgroup>
                            </select>
                        </div>
                    </div><br /><br />
                    <div class="form-group">
                        <label for="ticket-subject" class="col-sm-3 control-label">Type</label>
                        <div class="col-sm-9">
                            <label class="control-inline fancy-checkbox">
                                <input id="credit" type="checkbox" name="Type" value="true">
                                <span>Credit</span>
                            </label>
                            <label class="control-inline fancy-checkbox">
                                <input id="debit" type="checkbox" name="Type" value="false" checked>
                                <span>Debit</span>
                            </label>
                        </div>
                    </div><br /><br />
                    <div class="form-group">
                        <label for="ticket-name" class="col-sm-3 control-label">Amount</label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control dannymagic", placeholder = "Amount", min = "0" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div><br />
                </fieldset>
                <fieldset class="transactions">
                    <legend style="font-size: 16px">Optional Info</legend>
                    <div class="form-group">
                        <label for="ticket-message" class="col-sm-3 control-label">Description</label>
                        <div class="col-sm-9">
                            <textarea class="form-control" name="Description" id="ticket-message" rows="5" cols="30" placeholder="Message"></textarea>
                        </div>
                    </div><br /><br />
                    <div class="form-group" style="margin-top: 85px">
                        <label for="ticket-attachment" class="col-sm-3 control-label">Receipt</label>
                        <div class="col-md-9">
                            <input name="image" type="file" id="fileUpload" />
                            @Html.ValidationMessageFor(model => model.Documentation, "", new { @class = "text-danger" })
                            <p class="help-block" style="font-size: 10px"><em>Valid file type: .jpg, .png, .gif. File size max: 1 MB</em></p>
                        </div>
                    </div><br /><br />
                    <div class="modal-footer" style="padding-bottom: 0px; margin-bottom: -20px">
                        <audio id="mysoundclip" preload="auto">
                            <source src="~/assets/audio/cash.wav" />
                        </audio>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times-circle"></i> Close</button>
                        <button type="submit" class="play btn btn-custom-primary"><i class="fa fa-check-circle"></i>Commit Transaction</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
}

@*@section Scripts {*@
<script src="~/assets/js/jquery/jquery-2.1.0.min.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
<script>
    $(document).on("keypress", ".dannymagic", function () {
        if (event.which == 45 || event.which == 109 || event.which == 189) {
            event.preventDefault();
        }
    });
</script>
<script>
    var audio = $("#mysoundclip")[0];
    console.log(audio);
    var vid = document.getElementById("mysoundclip");
    vid.volume = 0.2;
    $("button.play").click(function() {
        audio.play();
    });
</script>
@*}*@

Ryan_Budget/Views/Transactions/Edit.cshtml
@model Ryan_Budget.Models.Transaction

@{
    ViewBag.Title = "Edit";

}

<h2>Edit Transaction</h2>


@using (Html.BeginForm("Edit", "Transactions", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="act" value="@ViewBag.Account" />

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Documentation)

        <div class="form-group">
            <div class="control-label col-md-2">
                Transaction Date
            </div>
            <div class="col-md-10">
                <div class="input-group" style="color: #fff">
                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                    <input type="text" name="TransactionDate" class="datepickerTwo form-control" value="@Model.TransactionDate.ToString("mM/dd/yyyy")">
                    @Html.ValidationMessageFor(model => model.TransactionDate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                Account
            </div>
            <div class="col-md-10">
                @Html.DropDownList("AccountId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                Category
            </div>
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model.Type == false)
                {
                    <label class="control-inline fancy-checkbox">
                        <input class="credit" type="checkbox" name="Type" value="true">
                        <span>Credit</span>
                    </label>
                    <label class="control-inline fancy-checkbox">
                        <input class="debit" type="checkbox" checked name="Type" value="false">
                        <span>Debit</span>
                    </label>
                }
                @if (Model.Type == true)
                {
                    <label class="control-inline fancy-checkbox">
                        <input class="credit" type="checkbox" checked name="Type" value="true">
                        <span>Credit</span>
                    </label>
                    <label class="control-inline fancy-checkbox">
                        <input class="debit" type="checkbox"  name="Type" value="false">
                        <span>Debit</span>
                    </label>
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control dannymagic" name="Amount" min="0" value="@Math.Abs(Model.Amount)"/>
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>    
        <div class="form-group">
            <div class="control-label col-md-2">
                Receipt
            </div>
            <div class="col-md-10">
                <input name="image" type="file" class="form-control" id="fileUploadTwo" />
                <div id="fileDisplay" style="max-width: 400px; padding-top: 10px">
                    @Html.ValidationMessageFor(model => model.Documentation, "", new { @class = "text-danger" })
                    @if (Model.Documentation != null)
                    {
                        <a href="@Url.Content(Model.Documentation)"><img src="@Url.Content(Model.Documentation)" style="width: 90%; padding-top: 15px" /></a>
                    }
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Transactions", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
            var fileInput = document.getElementById('fileUploadTwo');
            var fileDisplayArea = document.getElementById('fileDisplay');

            //File Reader Function for displaying images
            fileInput.addEventListener('change', function (e) {
                var file = fileInput.files[0];
                var imageType = /image.*/;

                if (file.type.match(imageType)) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        fileDisplayArea.innerHTML = "";

                        // Create a new image.
                        var img = new Image();
                        // Set the img src property using the data URL.
                        img.src = reader.result;
                        // Add the image to the page.
                        fileDisplayArea.appendChild(img);
                    }

                    reader.readAsDataURL(file);
                }

                else {
                    fileDisplayArea.innerHTML = "File not supported!";
                }
            });
    </script>
    <script>
        $(document).ready(function () {
            $('.datepickerTwo').datepicker().on('changeDate', function (ev) {
                $(this).datepicker('hide');
            });
            $(".credit").click(function () {
                $('.debit').removeAttr("checked");
            });
            $(".debit").click(function () {
                $('.credit').removeAttr("checked");
            });
        });
    </script>
    <script>
        $(document).on("keypress", ".dannymagic", function () {
            if (event.which == 45 || event.which == 109 || event.which == 189) {
                event.preventDefault();
            }
        });
    </script>
}

Ryan_Budget/Views/Transactions/Index.cshtml
@model IEnumerable<Ryan_Budget.Models.Transaction>
@using Microsoft.AspNet.Identity;
@using Ryan_Budget.Models;

@{
    ViewBag.Title = "Index";
    ApplicationDbContext db = new ApplicationDbContext();
    var user = db.Users.Find(User.Identity.GetUserId());
    Layout = null;
}

<h2>Transaction Index</h2>
<hr />

<div class="widget widget-table">
    @*<div class="widget-header" style="padding-top: 5px">
        <h3 style="font-size: 18px"><i class="fa fa-home" style="padding-right: 5px"></i> Households</h3>
        <div class="btn-group widget-header-toolbar">
        </div>
    </div>*@
    <div class="widget-content">
        <table id="datatable-data-export-ryan" class="table table-hover table-bordered datatable">
            <thead>
                <tr>
                    <th>Posted Date</th>
                    <th>Transaction Date</th>
                    <th>Account</th>
                    <th>User</th>
                    <th>Category</th>
                    <th>Credits</th>
                    <th>Debits</th>
                    <th>Reconciled</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr style="font-size: 10px">
                        <td>
                            @item.Created.ToString("d")
                        </td>
                        <td>
                            @item.TransactionDate.ToString("d")
                        </td>
                        <td>
                            @item.Account.Name
                        </td>
                        <td>
                            @item.AuthorUser.FirstName
                        </td>
                        <td>
                            @item.Category.Name
                            @if (item.Description != null)
                            {
                            <i class="fa fa-question-circle" style="color:#1fa67a; margin-left: 3px; font-size: 12px" data-toggle="tooltip" data-placement="right" data-original-title="@item.Description"></i>
                            }
                        </td>
                        <td>
                            @if ((item.Amount >= 0) && (item.Status != "VOID"))
                            {
                                <strong style="color: #1fa67a">@String.Format("{0:C}", item.Amount)</strong> if (item.Documentation != null){<a href="@Url.Content(item.Documentation)" target="_blank"><i class="fa fa-file-text"></i></a>}
                            }
                            else if ((item.Amount >= 0) && (item.Status == "VOID"))
                            {
                                <em style="color: grey; text-decoration: line-through">@String.Format("{0:C}", item.Amount)</em> if (item.Documentation != null){<a href="@Url.Content(item.Documentation)" target="_blank"><i class="fa fa-file-text"></i></a>}
                            }
                        </td>
                        <td>
                            @if ((item.Amount < 0) && (item.Status != "VOID"))
                            {
                                <strong style="color: #d9534f">@String.Format("{0:C}", item.Amount)</strong> if (item.Documentation != null){<a href="@Url.Content(item.Documentation)" target="_blank"><i class="fa fa-file-text"></i></a>}
                            }
                            else if ((item.Amount < 0) && (item.Status == "VOID"))
                            {
                                <em style="color: grey; text-decoration: line-through">@String.Format("{0:C}", item.Amount)</em> if (item.Documentation != null){<a href="@Url.Content(item.Documentation)" target="_blank"><i class="fa fa-file-text"></i></a>}
                            }
                        </td>
                        <td>
                            @if(item.Reconciled == true)
                            {
                            <i class="fa fa-check-square-o" style="color: #1fa67a"></i>
                            }
                        </td>
                        <td>
                            @if (item.Status == "VOID")
                            {
                                <strong>@item.Status</strong> <a href="@Url.Action("Unvoid", "Transactions", new { id = item.Id } )"><i class="fa fa-undo"></i></a>
                            }
                            else if (item.Status == "RECONCILIATION")
                            {
                                <strong>@item.Status</strong>
                            }
                            else
                            {
                                <a href="@Url.Action("Edit", "Transactions", new { id = item.Id } )"><i class="fa fa-edit" style="font-size: 12px"></i></a> <span style="font-size: 12px">|</span>
                                <a href="@Url.Action("Void", "Transactions", new { id = item.Id } )"><i class="fa fa-ban" style="font-size: 12px"></i></a> <span style="font-size: 12px">|</span>
                                <a href="@Url.Action("Delete", "Transactions", new { id = item.Id } )"><i class="fa fa-trash" style="font-size: 12px"></i></a>                           
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@*@section scripts {*@
    <script>
        $(document).ready(function () {
            $('#datatable-data-export-ryan').dataTable({
                "bSort": false,                
            });
        });
    </script>
@*}*@