Ryan_Budget/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Ryan_Budget.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ExternalLoginListViewModel
    {
        public string ReturnUrl { get; set; }
    }

    public class SendCodeViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class VerifyCodeViewModel
    {
        [Required]
        public string Provider { get; set; }

        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }
        public string ReturnUrl { get; set; }

        [Display(Name = "Remember this browser?")]
        public bool RememberBrowser { get; set; }

        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Profile Picture")]
        public string ProfilePic { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

Ryan_Budget/Models/Code First/Account.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Ryan_Budget.Models
{
    public class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();          
        }
       
        public int Id { get; set; }
        public int HouseholdId { get; set; }
        [Required]
        public decimal Balance { get; set; }
        [Required]
        public string Name { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }
        public DateTimeOffset? LastDateReconciled { get; set; }

        public virtual Household Household { get; set; }

        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}

Ryan_Budget/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ryan_Budget.Models;
using Microsoft.AspNet.Identity;

namespace Ryan_Budget.Controllers
{
    [RequireHttps]
    public class AccountsController : UserNames
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Accounts
        [Authorize]
        public ActionResult Index()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var accounts = db.Accounts.Where(a => a.HouseholdId == user.HouseholdId);
            return View(accounts.ToList());
        }

        // GET: Accounts/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);


            if (account == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != account.HouseholdId)
            {
                return RedirectToAction("Warning", "Household");
            }

            ViewBag.AccountName = account.Name;
            ViewBag.Transactions = db.Transactions.Where(t => t.AccountId == account.Id).OrderByDescending(t => t.Id).ToList();
            return View(account);
        }

        // GET: Accounts/Create
        [Authorize]
        public ActionResult Create(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Household household = db.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != id)
            {
                return RedirectToAction("Warning", "Household");
            }

            ViewBag.HouseholdName = household.Name;
            ViewBag.HouseholdId = household.Id;      
            return View();
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HouseholdId,Balance,Name,Created,Updated,LastDateReconciled")] Account account)
        {
            ApplicationUser user = db.Users.FirstOrDefault(u => u.UserName.Equals(User.Identity.Name));
            var userid = user.Id;
            var created = System.DateTime.Now;

            if (ModelState.IsValid)
            {
                account.Created = System.DateTime.Now;
                db.Accounts.Add(account);
                db.SaveChanges();

                foreach (var member in user.Household.Users)
                {
                    Notification n = new Notification()
                    {
                        HouseholdId = user.Household.Id,
                        AccountId = account.Id,
                        AuthorUserId = userid,
                        UserToNotifyId = member.Id,
                        Created = created,
                        Type = "New Account",
                        Description = "New Account: " + account.Name,
                    };
                    db.Notifications.Add(n);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            Household household = db.Households.Find(account.HouseholdId);
            ViewBag.HouseholdName = household.Name;

            return View(account);
        }

        // GET: Accounts/Edit/5
        public ActionResult Edit(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);

            if (account == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != account.HouseholdId)
            {
                return RedirectToAction("Warning", "Household");
            }

            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HouseholdId,Balance,Name,Created,Updated,LastDateReconciled")] Account account)
        {
            if (ModelState.IsValid)
            {
                account.Updated = System.DateTimeOffset.Now;
                db.Accounts.Attach(account);
                db.Entry(account).Property("Name").IsModified = true;
                db.Entry(account).Property("Updated").IsModified = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(account);
        }

        // GET: Accounts/Reconcile/5
        [Authorize]
        public ActionResult Reconcile(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);

            if (account == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != account.HouseholdId)
            {
                return RedirectToAction("Warning", "Household");
            }

            return View(account);
        }

        // POST: Accounts/Reconcile/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Reconcile([Bind(Include = "Id,HouseholdId,Balance,Name,Created,Updated,LastDateReconciled")] Account account)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            Account oldAcct = db.Accounts.AsNoTracking().FirstOrDefault(a => a.Id == account.Id);

            if (ModelState.IsValid)
            {
                account.Updated = System.DateTimeOffset.Now;
                account.LastDateReconciled = System.DateTimeOffset.Now;
                db.Accounts.Attach(account);
                db.Entry(account).Property("LastDateReconciled").IsModified = true;
                db.Entry(account).Property("Updated").IsModified = true;
                db.Entry(account).Property("Balance").IsModified = true;
                db.SaveChanges();

                if (oldAcct?.Balance != account.Balance)
                {
                    if (oldAcct?.Balance > account.Balance)
                    {
                        var diff = oldAcct.Balance - account.Balance;

                        Transaction t = new Transaction
                        {
                            Created = System.DateTimeOffset.Now,
                            TransactionDate = System.DateTimeOffset.Now,
                            AccountId = account.Id,
                            Status = "RECONCILIATION",
                            Type = false,
                            Reconciled = true,
                            AuthorUserId = user.Id,
                            CategoryId = 23,
                            Amount = diff * -1,
                        };
                        db.Transactions.Add(t);
                        db.SaveChanges();
                    }

                    if (oldAcct?.Balance < account.Balance)
                    {
                        var diff = account.Balance - oldAcct.Balance;

                        Transaction t = new Transaction
                        {
                            Created = System.DateTimeOffset.Now,
                            TransactionDate = System.DateTimeOffset.Now,
                            AccountId = account.Id,
                            Status = "RECONCILIATION",
                            Type = true,
                            Reconciled = true,
                            AuthorUserId = user.Id,
                            CategoryId = 6,
                            Amount = diff,
                        };
                        db.Transactions.Add(t);
                        db.SaveChanges();
                    }

                }

                var transactions = db.Transactions.Where(t => t.AccountId == account.Id).ToList();
                foreach (var trans in transactions)
                {
                    trans.Reconciled = true;
                    db.SaveChanges();
                }                   

                return RedirectToAction("Index");
            }

            return View(account);
        }

        // GET: Accounts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);


            if (account == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != account.HouseholdId)
            {

Ryan_Budget/Views/Accounts/Create.cshtml
@model Ryan_Budget.Models.Account

@{
    ViewBag.Title = "Create";
}

<h2>Add Account</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@ViewBag.HouseholdId" name="HouseholdId"/>

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HouseholdId, "Household Name", htmlAttributes: new { @class = "control-label col-md-2", style="padding-top: 10px" })
            <div class="col-md-10" style="color: #1fa67a; font-size: 24px;">
                @ViewBag.HouseholdName
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control", type="decimal" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Accounts", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ryan_Budget/Views/Accounts/Delete.cshtml
@model Ryan_Budget.Models.Account

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Account</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Household.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Household.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastDateReconciled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastDateReconciled)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
        </div>

        <div>
            @Html.ActionLink("Back to Accounts", "Index")
        </div>
    }
</div>

Ryan_Budget/Views/Accounts/Details.cshtml
@model Ryan_Budget.Models.Account

@{
    ViewBag.Title = "Index";
}

<h2>@ViewBag.AccountName - Transactions</h2>
Balance: 
@if (Model.Balance >= 0)
{
    <div class="label" style="margin-left: 5px; display: inline-block; background-color: #1fa67a; font-size: 12px; box-shadow: 2px 2px 5px black">@String.Format("{0:C}", Model.Balance)</div>
}
else
{
    <div class="label" style="margin-left: 5px; display: inline-block; background-color: #d9534f; font-size: 12px; box-shadow: 2px 2px 5px black">@String.Format("{0:C}", Model.Balance)</div>
}
<hr />

<div class="widget widget-table">
    @*<div class="widget-header" style="padding-top: 5px">
            <h3 style="font-size: 18px"><i class="fa fa-home" style="padding-right: 5px"></i> Households</h3>
            <div class="btn-group widget-header-toolbar">
            </div>
        </div>*@
    <div class="widget-content">
        <table id="datatable-data-export-ryan" class="table table-hover table-bordered datatable">
            <thead>
                <tr>
                    <th>Posted Date</th>
                    <th>Transaction Date</th>
                    <th>User</th>
                    <th>Category</th>
                    <th>Credits</th>
                    <th>Debits</th>
                    <th>Reconciled</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.Transactions)
                {
                    <tr style="font-size: 10px">
                        <td>
                            @item.Created.ToString("d")
                        </td>
                        <td>
                            @item.TransactionDate.ToString("d")
                        </td>
                        <td>
                            @item.AuthorUser.FirstName
                        </td>
                        <td>
                            @item.Category.Name
                            @if (item.Description != null)
                            {
                                <i class="fa fa-question-circle" style="color:#1fa67a; margin-left: 3px; font-size: 12px" data-toggle="tooltip" data-placement="right" data-original-title="@item.Description"></i>
                            }
                        </td>
                        <td>
                            @if ((item.Amount >= 0) && (item.Status != "VOID"))
                            {
                                <strong style="color: #1fa67a">@String.Format("{0:C}", item.Amount)</strong> if (item.Documentation != null){<a href="@Url.Content(item.Documentation)" target="_blank"><i class="fa fa-file-text"></i></a>}
                            }
                            else if ((item.Amount >= 0) && (item.Status == "VOID"))
                            {
                                <em style="color: grey; text-decoration: line-through">@String.Format("{0:C}", item.Amount)</em> if (item.Documentation != null){<a href="@Url.Content(item.Documentation)" target="_blank"><i class="fa fa-file-text"></i></a>}
                            }
                        </td>
                        <td>
                            @if ((item.Amount < 0) && (item.Status != "VOID"))
                            {
                                <strong style="color: #d9534f">@String.Format("{0:C}", item.Amount)</strong> if (item.Documentation != null){<a href="@Url.Content(item.Documentation)" target="_blank"><i class="fa fa-file-text"></i></a>}
                            }
                            else if ((item.Amount < 0) && (item.Status == "VOID"))
                            {
                                <em style="color: grey; text-decoration: line-through">@String.Format("{0:C}", item.Amount)</em> if (item.Documentation != null){<a href="@Url.Content(item.Documentation)" target="_blank"><i class="fa fa-file-text"></i></a>}
                            }
                        </td>
                        <td>
                            @if (item.Reconciled == true)
                            {
                                <i class="fa fa-check-square-o" style="color: #1fa67a"></i>
                            }
                        </td>
                        <td>
                            @if (item.Status == "VOID")
                            {
                                <strong>@item.Status</strong> <a href="@Url.Action("Unvoid", "Transactions", new { id = item.Id, act = item.AccountId } )"><i class="fa fa-undo"></i></a>

                            }
                            else if (item.Status == "RECONCILIATION")
                            {
                                <strong>@item.Status</strong>
                            }
                            else
                            {
                                <a href="@Url.Action("Edit", "Transactions", new { id = item.Id, act = item.AccountId } )"><i class="fa fa-edit"></i></a> <span>|</span>
                                <a href="@Url.Action("Void", "Transactions", new { id = item.Id, act = item.AccountId } )"><i class="fa fa-ban"></i></a> <span>|</span>
                                <a href="@Url.Action("Delete", "Transactions", new { id = item.Id, act = item.AccountId } )"><i class="fa fa-trash"></i></a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


@section scripts {
    <script>
        $(document).ready(function () {
            $('#datatable-data-export-ryan').dataTable({
                "bSort": false,
            });
        });
    </script>
}

Ryan_Budget/Views/Accounts/Edit.cshtml
@model Ryan_Budget.Models.Account

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Account</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Accounts", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ryan_Budget/Views/Accounts/Index.cshtml
@model IEnumerable<Ryan_Budget.Models.Account>
@using Microsoft.AspNet.Identity;
@using Ryan_Budget.Models;

@{
    ViewBag.Title = "Index";
    ApplicationDbContext db = new ApplicationDbContext();
    var user = db.Users.Find(User.Identity.GetUserId());
}

<h2>@user.Household.Name - Accounts</h2>
<a href="@Url.Action("Create", "Accounts", new { id = user.HouseholdId })"><div class="label" style="background-color: #1fa67a"><i class="fa fa-plus"></i> Add Account</div></a>
<hr />

<div class="widget widget-table">
    <div class="widget-content">
        <table id="ticket-table" class="table table-sorting table-hover table-bordered datatable">
            <thead>
                <tr>
                    <th>Account</th>
                    <th>Balance</th>
                    <th>Updated</th>
                    <th>Reconciled</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr style="font-size: 10px">
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @if (item.Balance >= 0)
                            {
                                <p style="color: #1fa67a"><strong>@String.Format("{0:C}", item.Balance)</strong></p>
                            }
                            else
                            {
                                <p style="color: #d9534f"><strong>@String.Format("{0:C}", item.Balance)</strong></p>

                            }
                        </td>
                        <td>
                            @if (item.Updated.HasValue)
                            {
                                @item.Updated.Value.ToString("d")
                            }
                        </td>
                        <td>
                            @if (item.LastDateReconciled.HasValue)
                            {
                                @item.LastDateReconciled.Value.ToString("d")
                            }
                        </td>
                        <td style="font-size: 12px">
                            <a href="@Url.Action("Edit", "Accounts", new { id = item.Id } )"><i class="fa fa-edit"></i></a> <span>|</span>
                            <a href="@Url.Action("Details", "Accounts", new { id = item.Id } )"><i class="fa fa-th-list"></i></a> <span>|</span>
                            <a href="@Url.Action("Reconcile", "Accounts", new { id = item.Id } )"><i class="fa fa-check-square-o"></i></a> <span>|</span>
                            <a href="@Url.Action("Delete", "Accounts", new { id = item.Id } )"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
<script>
</script>
}

Ryan_Budget/Views/Accounts/Reconcile.cshtml
@model Ryan_Budget.Models.Account

@{
    ViewBag.Title = "Reconcile";
}

<h2>Reconcile Account</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Name)

        <div class="form-group">
            @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control", type="decimal" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Accounts", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}