Ryan_Budget/Models/Code First/Budget.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Ryan_Budget.Models
{
    public class Budget
    {
        public int Id { get; set; }
        public int HouseholdId { get; set; }
        [Required]
        public decimal Amount { get; set; }
        [Required]
        public int FrequencyId { get; set; }
        public int? CategoryId { get; set; }
        [Required]
        public bool Type { get; set; }
        [Required]
        public string Description { get; set; }
        public string AuthorUserId { get; set; }
        public string UpdateUserId { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }

        public virtual Category Category { get; set; }
        public virtual Household Household { get; set; }
        public virtual ApplicationUser AuthorUser { get; set; }
        public virtual ApplicationUser UpdateUser { get; set; }
        public virtual Frequency Frequency { get; set; }
    }
}

Ryan_Budget/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ryan_Budget.Models;
using Microsoft.AspNet.Identity;

namespace Ryan_Budget.Controllers
{
    [RequireHttps]
    public class BudgetsController : UserNames
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Budgets
        [Authorize]
        public ActionResult Index()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var budgets = db.Budgets.Where(b => b.HouseholdId == user.HouseholdId);
            return View(budgets.ToList());
        }

        // GET: Budgets/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != budget.HouseholdId)
            {
                return RedirectToAction("Warning", "Household");
            }

            return View(budget);
        }

        // GET: Budgets/Create
        [Authorize]
        public ActionResult Create(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Household household = db.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != id)
            {
                return RedirectToAction("Warning", "Household");
            }

            ViewBag.HouseholdName = household.Name;
            ViewBag.HouseholdId = household.Id;
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            ViewBag.FrequencyId = new SelectList(db.Frequencies, "Id", "Length");

            return View();
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HouseholdId,Amount,FrequencyId,CategoryId,Type,Description,AuthorUserId,UpdateUserId,Created,Updated")] Budget budget)
        {
            ApplicationUser user = db.Users.FirstOrDefault(u => u.UserName.Equals(User.Identity.Name));
            var userid = user.Id;
            var created = System.DateTime.Now;

            if (ModelState.IsValid)
            {
                budget.Created = System.DateTime.Now;
                budget.AuthorUserId = user.Id;
                db.Budgets.Add(budget);
                db.SaveChanges();

                //foreach (var member in user.Household.Users)
                //{
                //    Notification n = new Notification()
                //    {
                //        HouseholdId = user.Household.Id,
                //        BudgetId = budget.Id,
                //        AuthorUserId = userid,
                //        UserToNotifyId = member.Id,
                //        Created = created,
                //        Type = "New Budget",
                //        Description = "New Budget For: " + budget.Category.Name,
                //    };
                //    db.Notifications.Add(n);
                //    db.SaveChanges();
                //}

                return RedirectToAction("Index");
            }

            Household household = db.Households.Find(budget.HouseholdId);
            ViewBag.HouseholdName = household.Name;
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", budget.CategoryId);
            ViewBag.FrequencyId = new SelectList(db.Frequencies, "Id", "Length", budget.FrequencyId);           

            return View(budget);
        }

        // GET: Budgets/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != budget.HouseholdId)
            {
                return RedirectToAction("Warning", "Household");
            }

            ViewBag.FrequencyId = new SelectList(db.Frequencies, "Id", "Length", budget.FrequencyId);
            return View(budget);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HouseholdId,Amount,FrequencyId,CategoryId,Type,Description,AuthorUserId,UpdateUserId,Created,Updated")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                budget.Updated = System.DateTimeOffset.Now;
                db.Budgets.Attach(budget);
                db.Entry(budget).Property("Amount").IsModified = true;
                db.Entry(budget).Property("FrequencyId").IsModified = true;
                db.Entry(budget).Property("Description").IsModified = true;
                db.Entry(budget).Property("Updated").IsModified = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FrequencyId = new SelectList(db.Frequencies, "Id", "Length", budget.FrequencyId);
            return View(budget);
        }

        // GET: Budgets/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            var user = db.Users.Find(User.Identity.GetUserId());

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }

            if (user.HouseholdId != budget.HouseholdId)
            {
                return RedirectToAction("Warning", "Household");
            }

            return View(budget);
        }

        // POST: Budgets/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ApplicationUser user = db.Users.FirstOrDefault(u => u.UserName.Equals(User.Identity.Name));
            var userid = user.Id;
            var created = System.DateTime.Now;
            Budget budget = db.Budgets.Find(id);
            db.Budgets.Remove(budget);
            db.SaveChanges();

            //foreach (var member in user.Household.Users)
            //{
            //    Notification n = new Notification()
            //    {
            //        HouseholdId = user.Household.Id,
            //        AuthorUserId = userid,
            //        UserToNotifyId = member.Id,
            //        Created = created,
            //        Type = "Budget Deleted",
            //        Description = "Budget Deleted For: " + budget.Category.Name,
            //    };
            //    db.Notifications.Add(n);
            //    db.SaveChanges();
            //}

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ryan_Budget/Views/Budgets/Create.cshtml
@model Ryan_Budget.Models.Budget

@{
    ViewBag.Title = "Create";
}

<h2>Add Budget</h2>


@using (Html.BeginForm("Create", "Budgets", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value="@ViewBag.HouseholdId" name="HouseholdId" />

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2", style = "margin-top: -6px" })
            <div class="col-md-10">
                <label class="control-inline fancy-checkbox">
                    <input id="income" type="checkbox" name="Type" value="true">
                    <span>Income</span>
                </label>
                <label class="control-inline fancy-checkbox">
                    <input id="expense" type="checkbox" name="Type" value="false" checked>
                    <span>Expense</span>
                </label>
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                Category
            </div>            
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                Frequency
            </div>
            <div class="col-md-10">
                @Html.DropDownList("FrequencyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FrequencyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control dannymagic", min = "0" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea class="form-control" name="Description" rows="5" placeholder="Message" required></textarea>
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Budgets", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
            $(document).ready(function () {               
                $("#income").click(function () {
                    $('#expense').removeAttr("checked");
                });
                $("#expense").click(function () {
                    $('#income').removeAttr("checked");
                });
            });
    </script>
    <script>
        $(document).on("keypress", ".dannymagic", function () {
            if (event.which == 45 || event.which == 109 || event.which == 189) {
                event.preventDefault();
            }
        });
    </script>
}

Ryan_Budget/Views/Budgets/Delete.cshtml
@model Ryan_Budget.Models.Budget

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Budget</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Frequency.Length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Frequency.Length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Household.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Household.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
        </div>

        <div>
            @Html.ActionLink("Back to Budgets", "Index")
        </div>
    }
</div>

Ryan_Budget/Views/Budgets/Details.cshtml
@model Ryan_Budget.Models.Budget

@{
    ViewBag.Title = "Details";
}

<h2>Budget Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Frequency.Length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Frequency.Length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Household.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Household.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to Budgets", "Index")
</p>

Ryan_Budget/Views/Budgets/Edit.cshtml
@model Ryan_Budget.Models.Budget

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Budget</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control dannymagic", min = "0" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                Frequency
            </div>
            <div class="col-md-10">
                @Html.DropDownList("FrequencyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FrequencyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea class="form-control" name="Description" rows="5">@Model.Description</textarea>
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Budgets", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
            $(document).on("keypress", ".dannymagic", function () {
                if (event.which == 45 || event.which == 109 || event.which == 189) {
                    event.preventDefault();
                }
            });
    </script>
}